### ISSUE TITLE
Directory not good

### ISSUE THREAD

**Issue by gamersalpha** [unlhcc/autofs#1]
hello, 
so i have a windows sharing like this : 
\\192.168.50.49\GoFlex Home Public

so now i want acess with autofos

`sudo nano /etc/autofs.master`

with

`/media/autofs/smb/ /etc/auto.mnt --ghost,--timeout=30`

and auto.mnt

`sudo nano /etc/auto.mnt`

`GoFlexHome -fstype=cifs,iocharset=utf8,credentials=/root/.share-credentials2,uid=1000,gid=1000 :"//192.168.50.49/GoFlex\ Home\ Public/"`

my problem is : 
autofs mount the directory in : 

`root@serv01:~# ls /media/autofs/smb/`

and not in  :

`ls: cannot access /media/autofs/smb/GoFlexHome/: No such file or directory`

so what is wrongin config file please

**Comment by djw8605** [comment]
Hi,

We do not support autofs.  We use it, but have very limited knowledge of autofs configuration.

Autofs is part of the base linux binaries.  I'm not even sure where to contact for help.  If you run `man autofs` on a linux system, you see this author information:

> This page is part of the autofs (automount) project.  Information about the project can be found at ⟨http://www.autofs.org/⟩.  If you have a bug report for this manual page, send it to autofs@vger.kernel.org.

Not that that helps at all.  The website doesn't work.  You may have the best luck asking over at https://serverfault.com/

Closing this ticket.
