### ISSUE TITLE
documentation link dead

### ISSUE THREAD

**Issue by alexmyczko** [unlhcc/autofs#3]
trying to open http://www.Linux-Consulting.com/Amd_AutoFS/autofs.html with a browser tells me: could not be found.

**Comment by ghjs** [comment]
This autofs repository is just a clone of the authors' upstream repository https://git.kernel.org/pub/scm/linux/storage/autofs/autofs.git/ with additions we are sharing publicly in our "hcc-make-shared" branch.

You can send patches to the autofs developers, the contact information is in the [README.](https://git.kernel.org/pub/scm/linux/storage/autofs/autofs.git/tree/README)
