### ISSUE TITLE
open Too many levels of symbolic links

### ISSUE THREAD

**Issue by zffocussss** [unlhcc/autofs#4]
hi I am using autofs.but sometimes I can have "open Too many levels of symbolic links" when I cd or ls

**Comment by acaprez** [comment]
Hi,

This autofs repository is just a clone of the authors' upstream repository https://git.kernel.org/pub/scm/linux/storage/autofs/autofs.git/ with additions we are sharing publicly in our "hcc-make-shared" branch.

We do not maintain, develop, or support autofs.  I would suggest you ask your question somewhere like [stackoverflow.com](https://stackoverflow.com) or [serverfault.com](https://serverfault.com).
